name: Workflow to run my tests
on: push
jobs:
  runTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1.0.0
      - run: npm install
      - run: npm test
        env: PORT = 4000
          WEATHER_STACK_ACCESS_KEY = somekey
          WEATHER_STACK_URL = http://api.weatherstack.com
          OPEN_NOTIFY_URL = http://api.open-notify.org
          OPEN_NOTIFY_URL_JSON = http://api.open-notify.org/iss-now.json
